repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-json
      - id: check-yaml

  - repo: local
    hooks:
      - id: npmDepsHash-not-placeholder
        name: npmDepsHash must not be placeholder
        language: pygrep
        entry: "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
        files: flake\.nix
        pass_filenames: false
