/// <reference path="../pb_data/types.d.ts" />

// Add a unique, indexed `slug` field to cups.
//
// The slug is generated by the import script from name + series + year
// (+ "-ornament" suffix for ornaments). It serves as the human-readable
// URL segment for cup detail pages: /cup/seattle-been-there-2018
//
// Existing records have no slug until the import script is re-run.
// The field is optional so the migration can run without a full re-import.
migrate(
  (app) => {
    const cups = app.findCollectionByNameOrId("cups");

    cups.fields.add(new TextField({
      name: "slug",
      required: false,
    }));

    // Unique index on slug — enforced only for non-empty values so records
    // without a slug (not yet backfilled) don't conflict with each other.
    cups.indexes.push("CREATE UNIQUE INDEX IF NOT EXISTS idx_cups_slug ON cups (slug) WHERE slug != ''");

    app.save(cups);
  },
  (app) => {
    const cups = app.findCollectionByNameOrId("cups");
    const field = cups.fields.getByName("slug");
    if (field) cups.fields.remove(field);
    cups.indexes = cups.indexes.filter((i) => !i.includes("idx_cups_slug"));
    app.save(cups);
  }
);
