name: Refresh Renovate npm hash

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    paths:
      - app/package-lock.json

permissions:
  contents: read

jobs:
  refresh:
    uses: genebean/.github/.github/workflows/renovate-npm-hash.yml@main
    with:
      npm-lock-file: app/package-lock.json
      npmDepsHash-glob: pkgs/app.nix
    secrets:
      token: ${{ secrets.CI_FLAKE_UPDATES }}
